[package]
name = "algorithm_challenges"
version = "0.1.0"
edition = "2024"

[dependencies]
bitvec = "1.0.1"
twox-hash = "2.1.2"
serde = { version = "1.0.228", features = ["derive"] }
sha2 = "0.10.9"
hex = "0.4.3"
rstest = "0.26.1"
